# Generated by Django 4.1.3 on 2022-11-25 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "coupon_id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "купон",
                "verbose_name_plural": "Купоны",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("price", models.IntegerField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "Товары",
                "ordering": ("name", "price"),
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(regex="\\d{8}")
                        ],
                        verbose_name="Код налога",
                    ),
                ),
            ],
            options={
                "verbose_name": "налог",
                "verbose_name_plural": "Налоги",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stripe_api.discount",
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(to="stripe_api.item", verbose_name="Товары"),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stripe_api.tax",
                verbose_name="Налог",
            ),
        ),
    ]
